services:
  - type: web
    name: cires-backend
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: cires-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: cires-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: cires-db
          property: password
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      # ADD THIS LINE BELOW
      - key: PORT
        value: 8081
      - key: JWT_SECRET
        value: 0b62960339444a8db6526c8ecfc45683

databases:
  - name: cires-db
    plan: free