services:
  - type: web
    name: cires-backend
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: cires-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: cires-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: cires-db
          property: password
      # This tells Spring to use Postgres instead of your local MySQL default
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: JWT_SECRET
        value: 0b62960339444a8db6526c8ecfc45683 # Using your unique key

databases:
  - name: cires-db
    plan: free